### ISSUE TITLE
How to obtain my systemid? 

### ISSUE THREAD

**Issue by ghost** [Hazuki-san/sai-2-cracker#1]
I don't really know how to find one...

**Comment by ghost** [comment]
> I don't really know how to find one...

Go to the Other > System ID > Copy id that it shows to you.

**Comment by ghost** [comment]
> > I don't really know how to find one...
> 
> Go to the Other > System ID > Copy id that it shows to you.

eh what is the Other thing (it isn't in settings nor in the control panel)

**Comment by Hazuki-san** [comment]
It's in SAI itself.
