### ISSUE TITLE
hello,

### ISSUE THREAD

**Issue by femothecool** [Hazuki-san/sai-2-cracker#2]
hello this is less of an issue and more asking how to use it,also asking if it is fully safe.thanks.

**Comment by Hazuki-san** [comment]
It is safe to use, it will modify the part that validates the license to make the program thinks the program is legitimate.

**Comment by femothecool** [comment]
> It is safe to use, it will modify the part that validates the license to make the program thinks the program is legitimate.

ok i see,but to use it do i execute paint tool sai 2 first and when they ask for the license i open the software or like do i open the software (saicrack) first?i am just kinda confused on what and how to use the crack tool as i am kinda new to the whole coding thing too

**Comment by Hazuki-san** [comment]
You will have to open SAI to obtain System ID first (see #1) and then open SAICrack.exe (make sure you have sai.exe in there and type/paste your System ID there. After that, press Enter, type "OK" and then open sai.exe again.

**Comment by femothecool** [comment]
i'll try this right away,thank
also is it normal that window say stuff like "we blocked this app cuz its from an unothaurized source" and all that?just to be fully sure

**Comment by Hazuki-san** [comment]
That's normal behavior from Windows, click on "More Info" and press "Run anyway".
